---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: instavote
  namespace: instavote
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fred-lev/instavote-deploy
