---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: github-instavote
  url: https://github.com/fred-lev/instavote-deploy
