---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: instavote
  namespace: instavote
spec:
  interval: 1m0s
  path: ./flux
  prune: false
  serviceAccountName: instavote
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
